// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SupplySourceId } from './SupplySource';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.delivery */
export type DeliveryId = string & { __brand: 'public.delivery' };

/** Represents the table public.delivery */
export default interface DeliveryTable {
	id: ColumnType<DeliveryId, DeliveryId | undefined, DeliveryId>;

	supplySourceId: ColumnType<SupplySourceId, SupplySourceId, SupplySourceId>;

	amount: ColumnType<number, number, number>;

	deliveredAt: ColumnType<Date, Date | string | undefined, Date | string>;

	deliveredByDiscordId: ColumnType<string, string, string>;

	deliveredByUsername: ColumnType<string, string, string>;

	isDeleted: ColumnType<boolean, boolean | undefined, boolean>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Delivery = Selectable<DeliveryTable>;

export type NewDelivery = Insertable<DeliveryTable>;

export type DeliveryUpdate = Updateable<DeliveryTable>;
