// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SupplySetId } from './SupplySet';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.operation */
export type OperationId = string & { __brand: 'public.operation' };

/** Represents the table public.operation */
export default interface OperationTable {
	id: ColumnType<OperationId, OperationId | undefined, OperationId>;

	setId: ColumnType<SupplySetId, SupplySetId, SupplySetId>;

	operationType: ColumnType<string, string, string>;

	performedByDiscordId: ColumnType<string, string, string>;

	performedByUsername: ColumnType<string, string, string>;

	details: ColumnType<unknown, unknown, unknown>;

	performedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Operation = Selectable<OperationTable>;

export type NewOperation = Insertable<OperationTable>;

export type OperationUpdate = Updateable<OperationTable>;
