// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as DeliveryTable } from './Delivery';
import type { default as SupplySourceTable } from './SupplySource';
import type { default as OperationTable } from './Operation';
import type { default as SupplySetTable } from './SupplySet';
import type { default as ServerTable } from './Server';

export default interface PublicSchema {
	delivery: DeliveryTable;

	supplySource: SupplySourceTable;

	operation: OperationTable;

	supplySet: SupplySetTable;

	server: ServerTable;
}
