// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SupplySetId } from './SupplySet';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.supply_source */
export type SupplySourceId = string & { __brand: 'public.supply_source' };

/** Represents the table public.supply_source */
export default interface SupplySourceTable {
	id: ColumnType<SupplySourceId, SupplySourceId | undefined, SupplySourceId>;

	setId: ColumnType<SupplySetId, SupplySetId, SupplySetId>;

	number: ColumnType<number, number, number>;

	consumptionRate: ColumnType<number, number, number>;

	stockpileCheckpoint: ColumnType<number, number | undefined, number>;

	checkpointTimestamp: ColumnType<Date, Date | string | undefined, Date | string>;

	lastManualUpdate: ColumnType<Date, Date | string | undefined, Date | string>;

	isDeleted: ColumnType<boolean, boolean | undefined, boolean>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type SupplySource = Selectable<SupplySourceTable>;

export type NewSupplySource = Insertable<SupplySourceTable>;

export type SupplySourceUpdate = Updateable<SupplySourceTable>;
