// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServerId } from './Server';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.supply_set */
export type SupplySetId = string & { __brand: 'public.supply_set' };

/** Represents the table public.supply_set */
export default interface SupplySetTable {
	id: ColumnType<SupplySetId, SupplySetId | undefined, SupplySetId>;

	serverId: ColumnType<ServerId, ServerId, ServerId>;

	channelId: ColumnType<string, string, string>;

	name: ColumnType<string, string, string>;

	mapImageUrl: ColumnType<string | null, string | null, string | null>;

	isDeleted: ColumnType<boolean, boolean | undefined, boolean>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type SupplySet = Selectable<SupplySetTable>;

export type NewSupplySet = Insertable<SupplySetTable>;

export type SupplySetUpdate = Updateable<SupplySetTable>;
